f=open("file.txt",'w')
f.write("ymmmy yummy yummy")
f.close()
f=open("file.txt",'r')
print(f.read())
f.close()
f=open("file.txt",'w')# overwrites the data
f.writelines("ymmmy yummy yummy\ntasty tasty tasty\nyummy yummy yummy\ntasty tasty tasty\nyummy yummy yummy\ntasty tasty tasty")
f.close()
f=open("file.txt",'r')
print(f.readline())
f.close()
f=open("file.txt","w")
states=["delhi"," ,","punjab"," ,","bihar"]
f.writelines(states)
f.close()
f=open("file.txt","r")
print(f.readlines())
f.close()
#seek function-->
f=open("file.txt","w")
states=["delhi"," ,","punjab"," ,","bihar"]
f.writelines(states)
f.close()
f=open("file.txt","r")
f.seek(10)
print(f.readlines())
f.close()
f=open("file.txt","w+")
f.write("hello world")
f.seek(0)
print(f.read())
f.close()
#
f=open("file.txt","r+")
f.write("hello")
f.seek(0)
print(f.read())
f.close()
#